### PR TITLE
changed package to get the newest coffee-script

### PR DESCRIPTION
**Pull request by chafnan**
Changed the package.json to depend on the the newest version of coffee-script.

### CODE REVIEW

**Comment by jgable** [comment]
I'm okay with this, but can you also update the index.js to use the new

```
require('coffee-script/register');
```

So that people after 1.7 will not be broken.

**Comment by chafnan** [comment]
I should have seen that.  It's changed.

**Comment by jgable** [comment]
Thanks for the contribution.  Published as version 0.0.10 now on NPM.

**Comment by chafnan** [comment]
Thanks for responding so quick!

**Pull request merged**
